meteor:
  countdown-minutes: 60
  reminder-times-minutes:
    - 45
    - 30
    - 15
    - 5
  warning-title: "§6☄ Метеорит приближается!"
  warning-subtitle: "Падение через %time% в районе X:%x% Z:%z%"

  flight:
    height: 200
    duration-seconds: 10
    trail-particles:
      - "FLAME"
      - "SMOKE_LARGE"
      - "FIREWORKS_SPARK"
    whistle-sound: "ENTITY_ARROW_SHOOT"
    flash-y: 100

  impact:
    sound: "ENTITY_GENERIC_EXPLODE"
    crater-size: 5
    crater-materials:
      - "OBSIDIAN"
      - "CRYING_OBSIDIAN"
    shake-radius: 50.0
    shake-duration-ticks: 60

  core:
    display-name: "§aРадиоактивный метеорит"
    custom-model-data: 0

  radiation:
    radius: 40.0
    progression-seconds: 20
    damage-half-heart-interval: 5
    damage-heart-interval: 3

  dome:
    radius: 15
    check-interval-seconds: 60
    glass-types:
      - "GLASS"
      - "WHITE_STAINED_GLASS"
      - "LIGHT_GRAY_STAINED_GLASS"
      - "GRAY_STAINED_GLASS"
      - "BLACK_STAINED_GLASS"
      - "BLUE_STAINED_GLASS"
      - "CYAN_STAINED_GLASS"
      - "GREEN_STAINED_GLASS"
      - "LIME_STAINED_GLASS"
      - "BROWN_STAINED_GLASS"
      - "ORANGE_STAINED_GLASS"
      - "YELLOW_STAINED_GLASS"
      - "RED_STAINED_GLASS"
      - "PURPLE_STAINED_GLASS"
      - "MAGENTA_STAINED_GLASS"
      - "PINK_STAINED_GLASS"
