meteor:
  height: 60
  fall-duration-ticks: 1200
  radius: 2.0
  horizontal-offset: 25.0
  block: "NETHERITE_BLOCK"
  trail-particles:
    - "FLAME"
    - "SMOKE_LARGE"
    - "CAMPFIRE_SIGNAL_SMOKE"
    - "CAMPFIRE_COSY_SMOKE"
  impact-particles:
    - "EXPLOSION"
    - "CAMPFIRE_COSY_SMOKE"
  impact-sound: "ENTITY_GENERIC_EXPLODE"
  impact-power: 20.0
  explosion-radius: 100.0
  block-destruction-radius: 50
  falling-sound: "ENTITY_PHANTOM_FLAP"
  shake-radius: 40.0
  shake-duration-ticks: 20
  shake-amplifier: 0
  impact-shake-radius: 80.0
  impact-shake-duration-ticks: 60
  impact-shake-amplifier: 1
  flash-radius: 80.0
  flash-duration-ticks: 60
  flash-dot-threshold: 0.85
  ruin-radius: 14
  crater-radius: 6
  crater-depth: 3
  bedrock-radius: 1
  ruin-blocks:
    - "NETHERRACK"
    - "COBBLESTONE"
    - "MAGMA_BLOCK"
    - "BLACKSTONE"
  radiation:
    duration-seconds: 12
    max-damage: 10.0
    min-damage: 1.0
    leather-reduction: 0.15
    armor-durability-loss: 1
